blank_issues_enabled: true
contact_links:
  - name: Questions
    url: https://github.com/scikit-activeml/scikit-activeml/discussions
    about: Ask questions and discuss with other scikit-activeml community members