#### This Template was inspired by [numpy](https://github.com/numpy/numpy/blob/main/.github/ISSUE_TEMPLATE/documentation.yml) and [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/main/.github/ISSUE_TEMPLATE/doc_improvement.yml)

name: Documentation improvement
description: Create a report to help us improve the documentation. Alternatively you can just open a pull request with the suggested change.
labels: [Documentation, 'Needs Triage']
title: "DOC: <Please write a comprehensive title after the 'DOC: ' prefix>"

body:
- type: textarea
  attributes:
    label: Describe the issue linked to the documentation
    description: >
      Tell us about the confusion introduced in the documentation.
  validations:
    required: true
- type: textarea
  attributes:
    label: Suggest a potential alternative/fix
    description: >
      Tell us how we could improve the documentation in this regard.
