# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Insert Version number
      run: |
        echo $GITHUB_REF
        RELEASE_VERSION=${GITHUB_REF#refs/*/}
        echo $RELEASE_VERSION
        sed -i -E "s/__version__ = .*/__version__ = \"$RELEASE_VERSION\"/" skactiveml/__init__.py
        cat skactiveml/__init__.py
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade -r requirements.txt
        pip install twine
        pip install wheel
    - name: Update Switcher
      run: |
        RELEASE_VERSIONS=$(git tag -l --sort=-creatordate)
        echo $RELEASE_VERSIONS
        CURRENT_VERSION=$(git tag -l --sort=-creatordate | head -n 1)
        echo $CURRENT_VERSION
        python .github/workflows/update_requirements.py --versions $RELEASE_VERSIONS --release_version $CURRENT_VERSION
    - uses: actions/checkout@v4
      with:
          ref: master
    - name: Commit and push changes
      run: |
        git config --global user.name AlexanderBenz
        git config --global user.email AlexanderBenz@users.noreply.github.com

        git add docs/_static/switcher.json
        git commit -m "update switcher for release"
        git push origin master
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Trigger realease documentation for scikit-activeml-docs
      run: |
        curl -H "Authorization: token ${{ secrets.DOCS_PAT }}" --request POST https://api.github.com/repos/AlexanderBenz/scikit-activeml-project-docs/dispatches -d "{\"event_type\":\"release\"}"
